name: Notify API schema updates

on:
  release:
    types:
      - released

env:
  EVENT_TYPE: api-schema-updated
  REPOSITORY_ACCOUNTING_SDK_CSHARP: freee/freee-accounting-sdk-csharp
  REPOSITORY_ACCOUNTING_SDK_JAVA: freee/freee-accounting-sdk-java
  REPOSITORY_ACCOUNTING_SDK_PHP: freee/freee-accounting-sdk-php

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: check context
        run: echo $CONTEXT | jq
        env:
          CONTEXT: ${{ toJson(github) }}
      # - name: Check
      #   if: ${{ ! startsWith('gi') }}

  # notify_to_accounting_sdk_csharp:
  #   name: Notify to accounting SDK for C#
  #   if: ${{ }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Send repository dispatch
  #       uses: octokit/request-action@v2.x
  #       with:
  #         route: POST /repos/:repo/dispatches
  #         repo: ${{ env.REPOSITORY_ACCOUNTING_SDK_CSHARP }}
  #         event_type: ${{ env.EVENT_TYPE }}
  #         client_payload: |
  #           origin_ref: ${{ github.ref }}
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}

  # notify_to_accounting_sdk_java:
  #   name: Notify to accounting SDK for Java
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Send repository dispatch
  #       uses: octokit/request-action@v2.x
  #       with:
  #         route: POST /repos/:repo/dispatches
  #         repo: ${{ env.REPOSITORY_ACCOUNTING_SDK_JAVA }}
  #         event_type: ${{ env.EVENT_TYPE }}
  #         client_payload: |
  #           origin_ref: ${{ github.ref }}
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}

  # notify_to_accounting_sdk_php:
  #   name: Notify to accounting SDK for PHP
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Send repository dispatch
  #       uses: octokit/request-action@v2.x
  #       with:
  #         route: POST /repos/:repo/dispatches
  #         repo: ${{ env.REPOSITORY_ACCOUNTING_SDK_PHP }}
  #         event_type: ${{ env.EVENT_TYPE }}
  #         client_payload: |
  #           origin_ref: ${{ github.ref }}
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
